apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: playwright-jsonrpc
  namespace: playwright-jsonrpc
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: playwright-jsonrpc
