apiVersion: v1
kind: Service
metadata:
  name: playwright-jsonrpc
  namespace: playwright-jsonrpc
  labels:
    app: playwright-jsonrpc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    # cloud.google.com/neg: '{"ingress": true}'  # For GCP
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: playwright-jsonrpc
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
